config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: "task_new"
  post "tasks/new", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: "task_display"
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  post "tasks/:id/edit", to: "tasks#update"
  patch "tasks/:id/edit", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.all.find(params[:id].to_i)
    @status = " not completed yet."
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_display_path(@task)
  end

  def edit
    @task = Task.all.find(params[:id].to_i)
  end

  def update
    @task = Task.find(params[:id].to_i)
    @task.update(task_params)
    redirect_to task_display_path(@task)
  end

  def destroy
    Task.find(params[:id].to_i).destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit this task here:</h1>
<%= form_for :task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <br>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <br>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks for today:</h1>
<ul style="list-style-type: none">
  <% @tasks.each do |task| %>
    <li><%= check_box_tag(task.title, value = 1, checked = task.completed) %><%= link_to task.title, task_display_path(task["id"].to_i) %> <%= link_to "🚮", task_display_path(task), method: "delete" %></li>    
  <% end %>
</ul>
<br>
<hr>
<br>
<div>
  <p><%= link_to "Create a new task!", task_new_path %></p>
</div>

app/views/tasks/new.html.erb
<h1>Create a new task here:</h1>
<%= form_for :task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <br>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1><span>
<%= link_to "Edit Task", task_edit_path %></span>
<div>
  <h2><%= @task.details %></h2>
</div>
<% @status = " completed." if @task.completed%>
<p><%= check_box_tag(@task.title, value = 1, checked = @task.completed) %>This task is<%= @status %></p>
<br>
<br>
<br>
<%= link_to "Go back to the list", tasks_path %>